### PR TITLE
fix invalid HTML code in shiny_prerendered documents

### LINKED ISSUE #1912: Invalid HTML in prerendered shiny documents
`rmarkdown::run()` on a Rmd document with `runtime: shiny_prerendered` serves invalid HTML.

Consider the follwing Rmd file _invalidhtml/invalidhtml.Rmd_ with contents
```
---
title: "Invalid HTML"
output: html_document
runtime: shiny_prerendered
---

This creates invalid HTML.
```

Running this document with
```R
rmarkdown::run("invalidhtml/invalidhtml.Rmd")
```

Will serve a document with the follwing invalid HTML (I removed most content for brevity)
```html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <script type="application/shiny-singletons"></script>
  <!-- text snippets removed -->
</head>
<body><!DOCTYPE html>

<html>

<head>
  <!-- text snippets removed -->
</head>
  <!-- text snippets removed -->
</body>
</html></body>
</html>
```

The problem is that rmarkdown is rendering the Rmd file to a standalone HTML document, and returning the whole HTML document in the shiny app's UI function. The UI function, however, expects only the body of the document.

I am not sure if this issue has not been discovered until now, or if it's accepted for simplicity (I think most major browsers accept this invalid HTML).

---

R session info:
```
R version 4.0.2 Patched (2020-07-13 r78838)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.4.2     
  graphics_4.0.2  grDevices_4.0.2 highr_0.8       htmltools_0.5.0
  jsonlite_1.7.1  knitr_1.30      magrittr_1.5    markdown_1.1   
  methods_4.0.2   mime_0.9        rlang_0.4.7     rmarkdown_2.4.1
  stats_4.0.2     stringi_1.5.3   stringr_1.4.0   tinytex_0.26   
  tools_4.0.2     utils_4.0.2     xfun_0.18       yaml_2.2.1     

Pandoc version: 2.7.3
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

### PR DESCRIPTION
**Pull request by dakep**
Resolves #1912. Instead of an HTML string containing the entire document (which is not recognized as stand-alone html document by shiny), return an *html_document* object with the dependencies already injected.

### CODE REVIEW

**Comment by johnbde** [comment]
Thanks a ton. By when this will be merged with rstudio:master?

File: R/shiny_prerendered.R [hunk 1]
```diff
@@ -159,7 +160,14 @@ shiny_prerendered_html <- function(input_rmd, render_args) {
     dependencies <- append(dependencies, list(html_dependency_rsiframe()))
 
   # return html w/ dependencies
-  shinyHTML_with_deps(rendered_html, dependencies)
+  html_with_deps <- shinyHTML_with_deps(rendered_html, dependencies)
+
+  # add placeholder for additional dependencies at the end of the <head> element
+  sub('</head>',
+      '\n<!-- HEAD_CONTENT -->\n</head>',
```
Comment (schloerke) [inline R/shiny_prerendered.R:167]:
```suggestion
      '\n{{ headContent() }}\n</head>',      
```

**Review by schloerke — APPROVED** [review]
I'd like to allow for `htmltools` to still have control over the `HEAD_CONTENT` comment that it looks for. We can use `{{ headContent() }}` instead to allow `htmltools` to change in the future (unlikely).

LGTM!(... given small change). Thank you for the changes!

File: R/shiny_prerendered.R [hunk 2]
```diff
@@ -69,11 +69,12 @@ shiny_prerendered_app <- function(input_rmd, render_args) {
   }
 
   # attach dependencies to final html
-  html <- htmltools::attachDependencies(html, deps)
+  html_doc <- htmltools::htmlTemplate(text_ = html, document_ = TRUE)
```
Comment (jcheng5) [inline R/shiny_prerendered.R:72]: I think we don't actually want template expansion to happen here, right? Otherwise if your Rmd happened to contain `{{blah}}` we'd try to evaluate it as R code! We just want the effects of `document_ = TRUE`. It might be better to just do that directly:

```r
html_doc <- tagList(HTML(html))
class(html_doc) <- c("html_document", class(html_doc))
```

File: R/shiny_prerendered.R (hunk 1 above)
Comment (jcheng5) [reply R/shiny_prerendered.R:167]: Given my suggestion above (to not send this through `htmlTemplate`) this suggestion would no longer work, but something like this would:
```suggestion
      paste0('\n', htmlTemplate(text_ = "{{ headContent() }}"), '\n</head>'),
```

File: R/shiny_prerendered.R [hunk 3]
```diff
@@ -69,11 +69,12 @@ shiny_prerendered_app <- function(input_rmd, render_args) {
...
+  html_doc <- htmltools::attachDependencies(html_doc, deps)
 
   # create shiny app
   shiny::shinyApp(
-    ui = function(req) html,
+    ui = function(req) html_doc,
```
Comment (jcheng5) [inline R/shiny_prerendered.R:77]: Unrelated to this change, but this can just be `ui = html_doc`, since the value is static

**Review by cderv — APPROVED** [review]
Thanks @jcheng5 and @schloerke for the review. 

@dakep I'll do the change and merge. Thanks a lot for this PR !

File: R/shiny_prerendered.R (hunk 3 above)
Comment (cderv) [reply R/shiny_prerendered.R:77]: @jcheng5 it seems it has been made a function to avoid caching of html_prerendered UI. See
https://github.com/rstudio/rmarkdown/commit/2de1b1de7c42f79bc40a798473b89aa46fef4e7b

Has it changed ? Should it be kept ?

**Comment by cderv** [comment]
Thanks @dakep !

File: R/shiny_prerendered.R [hunk 4]
```diff
@@ -159,7 +158,26 @@ shiny_prerendered_html <- function(input_rmd, render_args) {
     dependencies <- append(dependencies, list(html_dependency_rsiframe()))
 
   # return html w/ dependencies
-  shinyHTML_with_deps(rendered_html, dependencies)
+  html_with_deps <- shinyHTML_with_deps(rendered_html, dependencies)
+
+  # add placeholder for additional dependencies at the end of the <head> element
```
Comment (gadenbuie) [inline R/shiny_prerendered.R:163]: Adding the additional dependencies at the end of `<head>` feels like the right thing to do but unfortunately, it breaks previous behavior. Before this change the served document structure was (essentially):

```
shiny boilerplate:
|- head
|- body
   |- full prerendered document
      |- head
      |- body
```

so the dependencies added by shiny were in the first `<head>` tag and the document's dependencies appeared in the second `<head>` tag. When reconciled by the browser, this ends up being the same as

```
browser DOM
|- head
   |- shiny dependencies
   |- prerendered doc dependencies
```

In learnr, for example, this creates a situation where the scripts and dependencies in the tutorial's pandoc template appear _before_ the tutorial dependencies provided by learnr.

This may be the correct behavior and we can adjust in learnr, but I suspect there are other templates that take advantage of the implicit ordering of dependencies in the previous behavior.

Comment (cderv) [reply R/shiny_prerendered.R:163]: Followed in #2060 and fixed by #2064
