### PR TITLE
use `pandoc_to` directly to determine output type

### LINKED ISSUE #2113: `citation_package` does not work when `keep_tex` is false when rendering plain Markdown files
I'm not sure if this is expected behavior, but I can't find any documentation about it. When using `rmarkdown::render()` on a vanilla `.md` file, if a bibliography is specified in the YAML, the `citation_package` option does not get used and the generated pandoc command includes `--citeproc` instead of `--biblatex` or `--natbib`. However, if `keep_tex` is set to true, `citation_package` *does* get used and the specificed citation package shows up in the pandoc command. This is not the case when rendering R Markdown files. 

Thus the only way to use `citation_package` when working with vanilla Markdown is to also use `keep_tex: true`:

| File type | `keep_tex` | Option in pandoc command |
|-----------|----------|--------------------------|
| .md       | false    | `--citeproc`             |
| .md       | true     | `--biblatex`             |
| .Rmd      | false    | `--biblatex`             |
| .Rmd      | true     | `--biblatex`             |

---

Here's a reproducible example:

**`references.bib`** (a placeholder bibtex file)

```
@book{smith2021,
	author = {Jill Smith},
	publisher = {ABC Publishing},
	title = {Some neat title},
	year = {2021}}
```

**`testing.md`**

```
---
title: "Example"
output: 
  pdf_document: 
    citation_package: biblatex
    keep_tex: false
bibliography: references.bib
---

Testing [@smith2021].
```

Run `rmarkdown::render("testing.md")` (or press ⌘⇧K/the knit button) and the generated pandoc command will contain `--citeproc` and not contain `--biblatex`:

```r
rmarkdown::render('testing.md')
#> /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS testing.md --to latex 
#> --from markdown+autolink_bare_uris+tex_math_single_backslash --output testing.pdf --lua-filter 
#> /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua 
#> --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua
#> --self-contained --highlight-style tango --pdf-engine pdflatex 
#> --variable graphics --variable 'geometry:margin=1in' --citeproc 
```

But if I switch `keep_tex` to true and re-render, the generated pandoc will contain `--biblatex` as expected:

**`testing.md`**

```
---
title: "Example"
output: 
  pdf_document: 
    citation_package: biblatex
    keep_tex: true
bibliography: references.bib
---

Testing [@smith2021].
```

```r
rmarkdown::render("testing.md")
#> /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS testing.md --to latex 
#> --from markdown+autolink_bare_uris+tex_math_single_backslash --output testing.tex --lua-filter 
#> /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua 
#> --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua 
#> --self-contained --highlight-style tango --pdf-engine pdflatex --biblatex 
#> --variable graphics --variable 'geometry:margin=1in' 
```

---

If I rename `testing.md` to `testing.Rmd` and run `rmarkdown::render('testing.Rmd')`, `--biblatex` appears in the pandoc command both when `keep_tex` is true or false, as expected. `--biblatex` seems to only unexpectedly disappear when rendering a `.md` file to PDF with `keep_tex` set to false.

---

Here's my session info:

``` r
xfun::session_info('rmarkdown')
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
#> 
#> Package version:
#>   base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2       
#>   graphics_4.0.3    grDevices_4.0.3   highr_0.8         htmltools_0.5.1.1
#>   jsonlite_1.7.2    knitr_1.31        magrittr_2.0.1    markdown_1.1     
#>   methods_4.0.3     mime_0.10         rlang_0.4.10      rmarkdown_2.7.10 
#>   stats_4.0.3       stringi_1.5.3     stringr_1.4.0     tinytex_0.31     
#>   tools_4.0.3       utils_4.0.3       xfun_0.22         yaml_2.2.1       
#> 
#> Pandoc version: 2.11.4
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

### PR DESCRIPTION
**Pull request by cderv**
This fixes #2113 

When `.md` file is used instead of `.Rmd` file, **knitr** is not used and so **knitr** option are not set. This means that `knitr::is_latex_output()` will be FALSE. We need to test directly the `pandoc_to` variable retrieved from `output_formats$pandoc$to`. 

This is a quick fix for #2113 but basically we could also replace `knitr::is_latex_output()` as it will do the same when as `knitr::opts$get("rmarkdown.pandoc.to")` will be set to `pandoc_to`. Using `pandoc_to` directly would work.

```diff
diff --git a/R/render.R b/R/render.R
index 9e296cd5..3e933147 100644
--- a/R/render.R
+++ b/R/render.R
@@ -964,7 +964,7 @@ render <- function(input,
     # if the output format is LaTeX, first convert .md to .tex, and then convert
     # .tex to .pdf via latexmk() if PDF output is requested (in rmarkdown <=
     # v1.8, we used to call Pandoc to convert .md to .tex and .pdf separately)
-    if (output_format$pandoc$keep_tex || knitr::is_latex_output()
|| pandoc_to %in% c("latex", "beamer")) {
+    if (output_format$pandoc$keep_tex || pandoc_to %in% c("latex", "beamer")) {
       # do not use pandoc-citeproc if needs to build bibliography
       convert(texfile, run_citeproc && !need_bibtex)
       # patch the .tex output generated from the default Pandoc LaTeX template
```

We could also add a fallback value to `knitr::is_latex_output(fallback)` to internalize this 
This function would 
* checks `knitr::opts$set("out.format")`
* if FALSE, checks `knitr::opts$get("rmarkdown.pandoc.to")`
* if FALSE, checks the fallback format provided.

````r
is_latex_output <- function(fallback) {
    out_format("latex") || pandoc_to(c("latex", "beamer")) || fallback %in% c("latex", "beamer")
}
````

This is required if we want to indeed support `.md` file using `output:` key in the YAML header which is R Markdown thing in the first place - which suppose `.Rmd` extension usually.

### CODE REVIEW

File: R/render.R [hunk 1]
```diff
@@ -964,7 +964,7 @@ render <- function(input,
     # if the output format is LaTeX, first convert .md to .tex, and then convert
     # .tex to .pdf via latexmk() if PDF output is requested (in rmarkdown <=
     # v1.8, we used to call Pandoc to convert .md to .tex and .pdf separately)
-    if (output_format$pandoc$keep_tex || knitr::is_latex_output()) {
+    if (output_format$pandoc$keep_tex || knitr::is_latex_output() || pandoc_to %in% c("latex", "beamer")) {
```
Comment (yihui) [inline R/render.R:967]:
```suggestion
    if (output_format$pandoc$keep_tex || pandoc_to %in% c("latex", "beamer")) {
```

**Review by yihui — APPROVED** [review]
> Using `pandoc_to` directly would work.

That sounds cleaner to me. Thanks!

File: R/render.R (hunk 1 above)
Comment (cderv) [reply R/render.R:967]: Ok great ! I was not sure about the `out_format("latex")` format part in `knitr::is_latex_output()`. I guess it is not that important for **rmarkdown**. 

Thanks!
